### ISSUE TITLE
[Bug]: Tabs not showing until editing the dashboard then clicking done

### ISSUE THREAD

**Issue by i00** [kinghat/tabbed-card#146]
### Description

In 0.4.0-alpha the tabs don't show when you initially load the page.
When you edit the dashboard then click save it all shows

### Environment

```Markdown
- OS: Linux
- Browser: Chrome
- Home Assistant Version: 2024.4.4     
- Tabbed Card Version: 0.4.0-alpha
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
tabs:
  - card:
      type: history-graph
      entities:
        - sun.sun
    attributes:
      label: First
  - card:
      show_current: true
      show_forecast: true
      type: weather-forecast
      entity: weather.forecast_home
      forecast_type: daily
    attributes:
      label: Second
```

**Comment by i00** [comment]
DW - fixed in alpha.2

**Comment by i00** [comment]
DW - fixed in alpha.2

**Comment by adalovebass** [comment]
If I understand the original bug correctly, I am still having this issue on alpha.2.

To elaborate on what I'm experiencing, the "live card preview" to the right of the code editing area does not update at all, _until the changes are saved_ and the editor is re-opened. All my other cards have previews that update with any change to the content, so I feel confident this is specific to tabbed-card.

I am using the same code example as the original reporter. For comparison, creating a new `weather-forecast` card that does not use `tabbed-card` will show updates from the code editor immediately. For example, changing `show_forecast` from `true` to `false` will cause the card preview to update in real time.

## Environment:
```
- OS: Windows 10
- Browser: Chrome 126.0.6478.128
- Home Assistant Version: 2024.7.3
- Tabbed Card Version: 0.4.0-alpha.2
```

Thank you!
